
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Hinestroza
 */
public class CrearCuentas extends javax.swing.JFrame {

    static RegistroClientes registro = new RegistroClientes();
    public static Cuentas NuevasCuentas[][] = new Cuentas[5][5];
    static int autoincrementable = 10001;
    static int numerocuento = 0;
    static int numerocuento1 = 0;
    static int numerocuento2 = 0;
    static int numerocuento3 = 0;
    static int numerocuento4 = 0;
    MenuAdmin Administrador = new MenuAdmin();

    /**
     * Creates new form CrearCuentas
     */
    public CrearCuentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Ver Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton2.setText("CREAR CUENTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        

        String[][] matriz = new String[registro.ListaRegistradora.length][3];
        for (int i = 0; i < registro.ListaRegistradora.length; i++) {
            if (registro.ListaRegistradora[i] != null) {
                matriz[i][0] = String.valueOf(registro.ListaRegistradora[i].getCUI()); //columna 1 cui
                matriz[i][1] = registro.ListaRegistradora[i].getNombre(); // columna nombres
                matriz[i][2] = registro.ListaRegistradora[i].getApellido(); // apellidos
            }
        }
        String[] encabezado = {"CUI", "Nombre", "Apellido"};
        tablaDatos.setModel(new DefaultTableModel(
                matriz,
                encabezado
        ));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int fila = tablaDatos.getSelectedRow();

        if (fila == 0) {
            if (numerocuento < 5) {
                NuevasCuentas[fila][numerocuento] = new Cuentas(autoincrementable,
                        registro.ListaRegistradora[fila].getCUI(),
                        registro.ListaRegistradora[fila].getNombre(),
                        registro.ListaRegistradora[fila].getApellido(),
                        0);
                numerocuento++;
            }else{
                JOptionPane.showMessageDialog(null, "No puede agregar más cuentas");
                Administrador.setVisible(true);
                this.setVisible(false);
            }
        }
        if (fila == 1) {

            if (numerocuento1 < 5) {
                NuevasCuentas[fila][numerocuento1] = new Cuentas(autoincrementable,
                        registro.ListaRegistradora[fila].getCUI(),
                        registro.ListaRegistradora[fila].getNombre(),
                        registro.ListaRegistradora[fila].getApellido(),
                        0);
                numerocuento1++;
            }else{
                JOptionPane.showMessageDialog(null, "No puede agregar más cuentas");
                Administrador.setVisible(true);
                this.setVisible(false);
            }
        }
        if (fila == 2) {
            if (numerocuento2 < 5) {
                NuevasCuentas[fila][numerocuento2] = new Cuentas(autoincrementable,
                        registro.ListaRegistradora[fila].getCUI(),
                        registro.ListaRegistradora[fila].getNombre(),
                        registro.ListaRegistradora[fila].getApellido(),
                        0);
                numerocuento2++;
            }else{
                JOptionPane.showMessageDialog(null, "No puede agregar más cuentas");
                Administrador.setVisible(true);
                this.setVisible(false);
            }
        }
        if (fila == 3) {
            if (numerocuento3 < 5) {
                NuevasCuentas[fila][numerocuento3] = new Cuentas(autoincrementable,
                        registro.ListaRegistradora[fila].getCUI(),
                        registro.ListaRegistradora[fila].getNombre(),
                        registro.ListaRegistradora[fila].getApellido(),
                        0);
                numerocuento3++;
            }else{
                JOptionPane.showMessageDialog(null, "No puede agregar más cuentas");
                Administrador.setVisible(true);
                this.setVisible(false);
            }
        }
        if (fila == 4) {
            if (numerocuento4 < 5) {
                NuevasCuentas[fila][numerocuento4] = new Cuentas(autoincrementable,
                        registro.ListaRegistradora[fila].getCUI(),
                        registro.ListaRegistradora[fila].getNombre(),
                        registro.ListaRegistradora[fila].getApellido(),
                        0);
                numerocuento4++;
            }else{
                JOptionPane.showMessageDialog(null, "No puede agregar más cuentas");
                Administrador.setVisible(true);
                this.setVisible(false);
            }
        }
   
        autoincrementable++;
        this.setVisible(false);
        Administrador.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Administrador.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
