/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;

/**
 *
 * @author Hinestroza
 */
public class Transferencias extends javax.swing.JFrame {

    MenuAdmin Administrador = new MenuAdmin();
    CrearCuentas Cuentas = new CrearCuentas();
    static RegistroClientes registro = new RegistroClientes();
    static Hisotorial historia = new Hisotorial();

    /**
     * Creates new form Transferencias
     */
    public Transferencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VerDatos = new javax.swing.JButton();
        ListaCuentas = new javax.swing.JComboBox<>();
        VerCuentas = new javax.swing.JButton();
        Usuarios = new javax.swing.JComboBox<>();
        Transferencia = new javax.swing.JButton();
        VerDatos2 = new javax.swing.JButton();
        ListaCuentas1 = new javax.swing.JComboBox<>();
        VerCuentas2 = new javax.swing.JButton();
        Usuarios1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Cuenta Origen");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Usuario");

        VerDatos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        VerDatos.setText("Ver Datos");
        VerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDatosActionPerformed(evt);
            }
        });

        ListaCuentas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ListaCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCuentasActionPerformed(evt);
            }
        });

        VerCuentas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        VerCuentas.setText("Ver Cuentas");
        VerCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerCuentasActionPerformed(evt);
            }
        });

        Usuarios.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });

        Transferencia.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Transferencia.setText("Transferir");
        Transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferenciaActionPerformed(evt);
            }
        });

        VerDatos2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        VerDatos2.setText("Ver Datos");
        VerDatos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDatos2ActionPerformed(evt);
            }
        });

        ListaCuentas1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ListaCuentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCuentas1ActionPerformed(evt);
            }
        });

        VerCuentas2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        VerCuentas2.setText("Ver Cuentas");
        VerCuentas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerCuentas2ActionPerformed(evt);
            }
        });

        Usuarios1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Usuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuarios1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Cuenta Destino");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ListaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(VerCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(VerDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(Usuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ListaCuentas1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(VerCuentas2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(VerDatos2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(Transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VerDatos)
                        .addGap(24, 24, 24)
                        .addComponent(ListaCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(VerCuentas))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Usuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VerDatos2)
                        .addGap(24, 24, 24)
                        .addComponent(ListaCuentas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(VerCuentas2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Transferencia)
                    .addComponent(jButton1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDatosActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i < registro.ListaRegistradora.length; i++) {
            if (registro.ListaRegistradora[i] != null) {
                Usuarios.addItem(registro.ListaRegistradora[i].getCUI() + "  "
                        + registro.ListaRegistradora[i].getNombre()
                        + " " + registro.ListaRegistradora[i].getApellido());
            }
        }

    }//GEN-LAST:event_VerDatosActionPerformed

    private void ListaCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaCuentasActionPerformed

    private void VerCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerCuentasActionPerformed
        // TODO add your handling code here:

        int Numerocuenta = Usuarios.getSelectedIndex();
        if (Numerocuenta != -1) {
            //System.out.println(Numerocuenta);
            for (int i = 0; i < Cuentas.NuevasCuentas.length; i++) {
                if (Cuentas.NuevasCuentas[Numerocuenta][i] != null) {
                    ListaCuentas.addItem(String.valueOf(Cuentas.NuevasCuentas[Numerocuenta][i].getIdentificador())
                            + " " + Cuentas.NuevasCuentas[Numerocuenta][i].getCui() //EL numero toma en cuenta el numero de fila sin tomar 0
                            + " " + Cuentas.NuevasCuentas[Numerocuenta][i].getNombre()
                            + " " + Cuentas.NuevasCuentas[Numerocuenta][i].getApellido());
                    Transferencia.setVisible(true);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "numero invalido");
            this.setVisible(false);
            Administrador.setVisible(true);
        }
    }//GEN-LAST:event_VerCuentasActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariosActionPerformed

    private void TransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferenciaActionPerformed
        // TODO add your handling code here:
        int NumeroIdentificador = Usuarios.getSelectedIndex();
        int NumeroCuenta = ListaCuentas.getSelectedIndex();
        int NumeroIdentificador2 = Usuarios1.getSelectedIndex();
        int NumeroCuenta2 = ListaCuentas1.getSelectedIndex();

        if (NumeroCuenta != -1 && NumeroIdentificador != -1) {
            if (Cuentas.NuevasCuentas[NumeroIdentificador][NumeroCuenta].getIdentificador() != Cuentas.NuevasCuentas[NumeroIdentificador2][NumeroCuenta2].getIdentificador()) {
                int deposito = Integer.parseInt(JOptionPane.showInputDialog("Cuanto desea Transferir"));
                if (deposito <= 0) {
                    JOptionPane.showMessageDialog(rootPane, "Monto de Tranferencia invalido");
                } else {
                    if (Cuentas.NuevasCuentas[NumeroIdentificador][NumeroCuenta].getSaldo() - deposito < 0) {
                        JOptionPane.showMessageDialog(null, "No posee el saldo suficiente "
                                + Cuentas.NuevasCuentas[NumeroIdentificador][NumeroCuenta].getSaldo());
                    } else {
                        Cuentas.NuevasCuentas[NumeroIdentificador][NumeroCuenta].setSaldo(
                                Cuentas.NuevasCuentas[NumeroIdentificador][NumeroCuenta].getSaldo() - deposito);
                        Cuentas.NuevasCuentas[NumeroIdentificador2][NumeroCuenta2].setSaldo(
                                Cuentas.NuevasCuentas[NumeroIdentificador2][NumeroCuenta2].getSaldo() + deposito);
                        //JOptionPane.showMessageDialog(rootPane, "Tranferencia realizado con exito");
                        //System.out.println(Cuentas.NuevasCuentas[NumeroIdentificador][NumeroCuenta].getSaldo());
                        //System.out.println(Cuentas.NuevasCuentas[NumeroIdentificador2][NumeroCuenta2].getSaldo());
                        historia.Transacciones(NumeroIdentificador,NumeroCuenta, "retiro transferencia",deposito);
                        historia.Transacciones(NumeroIdentificador2, NumeroCuenta2, "transferencia", deposito);
                        
                        this.setVisible(false);
                        Administrador.setVisible(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "No puede trasnferia la misma cuenta de ");
                this.setVisible(false);
                Administrador.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ha ingresado una cuenta invalida no valido");
            this.setVisible(false);
            Administrador.setVisible(true);
        }
    }//GEN-LAST:event_TransferenciaActionPerformed

    private void VerDatos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDatos2ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < registro.ListaRegistradora.length; i++) {
            if (registro.ListaRegistradora[i] != null) {
                Usuarios1.addItem(registro.ListaRegistradora[i].getCUI() + "  "
                        + registro.ListaRegistradora[i].getNombre()
                        + " " + registro.ListaRegistradora[i].getApellido());
            }
        }
    }//GEN-LAST:event_VerDatos2ActionPerformed

    private void ListaCuentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCuentas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaCuentas1ActionPerformed

    private void VerCuentas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerCuentas2ActionPerformed
        // TODO add your handling code here:
        int Numerocuenta = Usuarios1.getSelectedIndex();
        if (Numerocuenta != -1) {
            //System.out.println(Numerocuenta);
            for (int i = 0; i < Cuentas.NuevasCuentas.length; i++) {
                if (Cuentas.NuevasCuentas[Numerocuenta][i] != null) {
                    ListaCuentas1.addItem(String.valueOf(Cuentas.NuevasCuentas[Numerocuenta][i].getIdentificador())
                            + " " + Cuentas.NuevasCuentas[Numerocuenta][i].getCui() //EL numero toma en cuenta el numero de fila sin tomar 0
                            + " " + Cuentas.NuevasCuentas[Numerocuenta][i].getNombre()
                            + " " + Cuentas.NuevasCuentas[Numerocuenta][i].getApellido());
                    Transferencia.setVisible(true);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "numero invalido");
            this.setVisible(false);
            Administrador.setVisible(true);
        }
    }//GEN-LAST:event_VerCuentas2ActionPerformed

    private void Usuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuarios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Usuarios1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Administrador.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaCuentas;
    private javax.swing.JComboBox<String> ListaCuentas1;
    private javax.swing.JButton Transferencia;
    private javax.swing.JComboBox<String> Usuarios;
    private javax.swing.JComboBox<String> Usuarios1;
    private javax.swing.JButton VerCuentas;
    private javax.swing.JButton VerCuentas2;
    private javax.swing.JButton VerDatos;
    private javax.swing.JButton VerDatos2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
